### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jakamoo33** [efraimrodrigues/WhaPy#1]
Traceback (most recent call last):
  File "sample.py", line 3, in <module>
    wap = whapy.WhaPy(whapy.Browser.firefox)
  File "/root/Desktop/WhaPy-master/whapy/WhaPy.py", line 58, in __init__
    self._driver = webdriver.Firefox()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 162, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

solve it?
thank you.

**Comment by efraimrodrigues** [comment]
This issue is related to **selenium**.

Take a look at the **geckodriver.log** file to get further information about this error. Also check if your geckodriver is compatible with the Firefox version. 

Please refer to this question and let me know how it turns out: 
[https://stackoverflow.com/questions/39547598/selenium-common-exceptions-webdriverexception-message-connection-refused](url)
