### ISSUE TITLE
Store is not defined

### ISSUE THREAD

**Issue by marceloudi** [efraimrodrigues/WhaPy#3]
After QRCode processing, it tries to get Store object:

Traceback (most recent call last):
  File "w.py", line 3, in <module>
    wap = whapy.WhaPy(whapy.Browser.firefox, True)
  File "/usr/local/lib/python3.5/dist-packages/whapy/WhaPy.py", line 86, in __init__
    while not self._driver.execute_script("return Store.Conn.me"):
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 629, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: ReferenceError: **Store is not defined**

Have you ever seen this message? It seems that code changed...

**Comment by efraimrodrigues** [comment]
I'm sorry but due WhatsApp recent updates to the whatsapp web service WhaPy has been discontinued.
